force-app/main/default/objects/Costs_Per_Product__c/Costs_Per_Product__c.object-meta.xml
<CustomObject>
    <description>Junction Object to relate the different costs of a type of Product (Standard, Black, Metal, etc) and a Home Country (Denmark, France, Spain. Italy, United Kingdom, etc)</description>
    <label>Costs_Per_Product</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Costs Per Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Costs_Per_Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Costs_Per_Product__c/fields/ATM_Fee__c.field-meta.xml
<CustomField>
    <fullName>ATM_Fee__c</fullName>
    <description>ATM Fee in other currencies</description>
    <label>ATM Fee</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Costs_Per_Product__c/fields/Card_Replacement_Cost__c.field-meta.xml
<CustomField>
    <fullName>Card_Replacement_Cost__c</fullName>
    <description>Card Replacement Cost</description>
    <label>Card Replacement Cost</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Costs_Per_Product__c/fields/Cost_per_Calendar_Month__c.field-meta.xml
<CustomField>
    <fullName>Cost_per_Calendar_Month__c</fullName>
    <description>Cost per Calendar Month</description>
    <label>Cost per Calendar Month</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Costs_Per_Product__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Custom Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ProductController_Test.cls
@isTest
private class ProductController_Test {

    @TestSetup
    static void setup(){
        Product__c prod = new Product__c(Name = 'Standard');
        insert prod;
        Costs_Per_Product__c cost = new Costs_Per_Product__c(Country__c = 'DE', Cost_per_Calendar_Month__c = 5.0, ATM_Fee__c = 1, Card_Replacement_Cost__c = 10.0);
        insert cost;
    }

    @isTest
    static void getProductInfoTest() {
        Map<String, String> output;
        Product__c prod = [SELECT Id FROM Product__c LIMIT 1];
        Costs_Per_Product__c cost = [SELECT Id,Country__c FROM Costs_Per_Product__c LIMIT 1];
        Test.startTest();
            output = ProductController.getProductInfo(prod.Id, cost.Country__c);
        Test.stopTest();
        Assert.areEqual('Standard', output.get('prodName'), 'Product names dont match');
    }
}