force-app/main/default/objects/Costs_Per_Product__c/Costs_Per_Product__c.object-meta.xml
<CustomObject>
    <description>Junction Object to relate the different costs of a type of Product (Standard, Black, Metal, etc) and a Home Country (Denmark, France, Spain. Italy, United Kingdom, etc)</description>
    <label>Costs_Per_Product</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Costs Per Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Costs_Per_Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Costs_Per_Product__c/fields/ATM_Fee__c.field-meta.xml
<CustomField>
    <fullName>ATM_Fee__c</fullName>
    <description>ATM Fee in other currencies</description>
    <label>ATM Fee</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Costs_Per_Product__c/fields/Card_Replacement_Cost__c.field-meta.xml
<CustomField>
    <fullName>Card_Replacement_Cost__c</fullName>
    <description>Card Replacement Cost</description>
    <label>Card Replacement Cost</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Costs_Per_Product__c/fields/Cost_per_Calendar_Month__c.field-meta.xml
<CustomField>
    <fullName>Cost_per_Calendar_Month__c</fullName>
    <description>Cost per Calendar Month</description>
    <label>Cost per Calendar Month</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Costs_Per_Product__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Costs_Per_Product__c/fields/Currency_Iso_Code__c.field-meta.xml
<CustomField>
    <fullName>Currency_Iso_Code__c</fullName>
    <formula>IF(ISPICKVAL(Country__c, &apos;UK&apos;),&apos;GBP&apos;, &apos;EUR&apos; )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Currency_Iso_Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Costs_Per_Product__c/fields/Custom_Product__c.field-meta.xml
<CustomField>
    <fullName>Custom_Product__c</fullName>
    <label>Custom Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Costs</relationshipLabel>
    <relationshipName>Costs_Per_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Custom Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ProductController.cls
public with sharing class ProductController {
    
    @AuraEnabled(cacheable=true)
    public static Map<String, String> getProductInfo(String productId, String country){
        Map<String, String> productData = new Map<String, String>();
        
        /*  Costs_Per_Product__c: custom object that relates cost of a product based on a country.
            Has different custom fields based on the differents types of costs: Cost_per_Calendar_Month__c, ATM_Fee__c, Card_Replacement_Cost__c    */
        Costs_Per_Product__c cost;

        if(!String.isEmpty(productId) || !String.isEmpty(country)){
             cost = [SELECT Id, Custom_Product__r.Name, Country__c, Currency_Iso_Code__c, Cost_per_Calendar_Month__c, ATM_Fee__c, Card_Replacement_Cost__c 
                                                FROM Costs_Per_Product__c where Custom_Product__c =: productId and Country__c =: country LIMIT 1];
        }
        if(cost != null){   //map product cost
            productData.put('prodName', cost.Custom_Product__r.Name);
            productData.put('currencyIsoCode', cost.Currency_Iso_Code__c);
            productData.put('costPerCalendarMonth', String.valueOf(cost.Cost_per_Calendar_Month__c));
            productData.put('atmFee', cost.ATM_Fee__c == null ? '' : String.valueOf(cost.ATM_Fee__c/100)); //coudl be undefined
            productData.put('cardReplacementCost', String.valueOf(cost.Card_Replacement_Cost__c));
        }else{
            throw new ProductControllerException('Product or country information costs is not available.');
        }

        return productData;
    }

    // Custom exception class used for ProductController exceptions
    public class ProductControllerException extends Exception {}
}