force-app/main/default/objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <label>Home_Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>DE</fullName>
                <label>Denmark</label>
            </value>
            <value>
                <fullName>FR</fullName>
                <label>France</label>
            </value>
            <value>
                <fullName>IT</fullName>
                <label>Italy</label>
            </value>
            <value>
                <fullName>ES</fullName>
                <label>Spain</label>
            </value>
            <value>
                <fullName>UK</fullName>
                <label>United Kingdom</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relationship to Product__c</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <description>External Unique Identifier</description>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Costs_Per_Product__c/Costs_Per_Product__c.object-meta.xml
<CustomObject>
    <description>Junction Object to relate the different costs of a type of Product (Standard, Black, Metal, etc) and a Home Country (Denmark, France, Spain. Italy, United Kingdom, etc)</description>
    <label>Costs_Per_Product</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Costs Per Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Costs_Per_Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Costs_Per_Product__c/fields/ATM_Fee__c.field-meta.xml
<CustomField>
    <fullName>ATM_Fee__c</fullName>
    <description>ATM Fee in other currencies</description>
    <label>ATM Fee</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Costs_Per_Product__c/fields/Card_Replacement_Cost__c.field-meta.xml
<CustomField>
    <fullName>Card_Replacement_Cost__c</fullName>
    <description>Card Replacement Cost</description>
    <label>Card Replacement Cost</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Costs_Per_Product__c/fields/Cost_per_Calendar_Month__c.field-meta.xml
<CustomField>
    <fullName>Cost_per_Calendar_Month__c</fullName>
    <description>Cost per Calendar Month</description>
    <label>Cost per Calendar Month</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Costs_Per_Product__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Costs_Per_Product__c/fields/Custom_Product__c.field-meta.xml
<CustomField>
    <fullName>Custom_Product__c</fullName>
    <label>Custom Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Costs</relationshipLabel>
    <relationshipName>Costs_Per_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Custom Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ContactAPI_Test.cls
@isTest
private class ContactAPI_Test {

    @TestSetup
    static void setup(){ 
        Product__c prod = new Product__c(Name = 'Standard');
        insert prod;
        
        Costs_Per_Product__c cost = new Costs_Per_Product__c(Custom_Product__c=prod.Id, Country__c = 'DE', Cost_per_Calendar_Month__c = 5.0, ATM_Fee__c = 1, Card_Replacement_Cost__c = 10.0);
        insert cost;

        Contact contact = new Contact(FirstName='Jane',LastName='Doe',
                                      Product__c=prod.Id, Home_Country__c='DE', UUID__c='ABC123');
        insert contact;
    }

    @isTest
    static void getContactProductAPITest() {
        RestRequest req = new RestRequest();
        req.requestURI = '/services/apexrest/contactproduct/ABC123';
        req.httpMethod = 'GET';
        RestContext.request = req;

        RestContext.response = new RestResponse();
        RestResponse response = RestContext.response;

        Test.startTest();
             ContactAPI.getContactProduct();
        Test.stopTest();

        Assert.areEqual(200, response.statusCode, 'API failed');
    }

    @isTest
    static void getContactProductAPIFailTest() {
        RestRequest req = new RestRequest();
        req.requestURI = '/services/apexrest/contactproduct/12345';
        req.httpMethod = 'GET';
        RestContext.request = req;

        RestContext.response = new RestResponse();
        RestResponse response = RestContext.response;

        Test.startTest();
             ContactAPI.getContactProduct();
        Test.stopTest();

        Assert.areEqual(400, response.statusCode, 'no contact for this uuid');
    }

}